### ISSUE TITLE
ტექსტების გადიდების ფუნქცია

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#1]

**Comment by Alexand227** [comment]
მომხმარებლების მხარეს არ მუშაობს ტექსტების გადიდების ფუნქცია

**Comment by Mari-a** [comment]
დამატებულია,

**Comment by davidgabrichidze** [comment]
@Zhestokus გამოქვეყნებულიც არის? გამოქვეყნება როგორი პერიოდულობით მოხდება?

Changelog-ს როგორ ვმართავთ?

@Alexand227 მარტივი release management-ია ასაწყობი.

**Comment by Alexand227** [comment]
@Zhestokus ეს საკითხი როგორ გვაქვს გადაწყვეტილი?
