### ISSUE TITLE
დაშბოარდის კონფიგურირება

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#11]

**Comment by Alexand227** [comment]
ვიცი გიყვარს ეს საქმე :)

**Comment by Zhestokus** [comment]
ხო არის ისედაც?

**Comment by Alexand227** [comment]
დაშბოარდის კონფიგურირება, რა გამოვიტანოთ და რა არა, რისთვისაც გაკეთდება ცალკე გვერდი

**Comment by davidgabrichidze** [comment]
@Zhestokus ეს რატომ დაიხურა?

გაკეთდა?

**Comment by Alexand227** [comment]
წესით გაკეთებულია. მარი რომ დიზაინებს დაადებს სათითაოდ უნდა გადავუარო ყველა საკითხს და თუ არ მუშაობს აღვადგენ.

**Comment by davidgabrichidze** [comment]
@Alexand227 მგონი აჯობებს, რომ Issue-ები შენ დახურო ხოლმე, შემოწმების შემდეგ, და არა პროგრამისტმა. 

შენ როგორ ფიქრობ?

**Comment by Alexand227** [comment]
კი, ეგ ეგრეც მოხდება საბოლოოდ, ერთიანად უნდა ჩამოვუარო ყველა საკითხს ისედაც.
