### ISSUE TITLE
ადმინის მხარეს ადმინისტრირების ინსტრუმენტები, მაგალითად როგორ უნდა დაემატოს ვიდეო, წიგნი, სტატია. (როგორც ქართული ასე ინგლისური) - ანუ ფეიჯის დუბლირება?

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#13]

**Comment by Zhestokus** [comment]
დამატებულია 
1. Video-ების დამატება წაშლის გვერდი
2. EBook-ების დამატება წაშლის გვერდი
3. Link-ების (როგორც ქვედა ძირითადი ისევე ქვე Link-ების) დამატება წაშლის გვერდი

ასევე დაკომიტებულია
