### ISSUE TITLE
მრავალენოვანი მონაცემების მხარდაჭერა

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#14]
როგორ მოვახდინოთ ცხრილების თარგმნა?
ტექსტური სვეტები იყოს გამრავლებული?
ანუ რიცხვები დარჩეს იგივე, ხოლო ტექსტური სვეტები იყოს გაორმაგებული?

**Comment by Zhestokus** [comment]
ეს პრობლემა იდეაში გადაჭრილია ჩერეზ Trnalation
ანუ რა ენაზეც უნდა იმ ენაზე შეიყვანოს და მერე Translation-ის საშუალებით გადათარგმნის
ვფიქრობ ესე უფრო მოხერხებული იქნება... ახალი ენის დამატებისას და სამუშაოც ნაკლები გამოვა რადგან ყველა გვერდზე და ყველა ტექსტური ველისტვის ორ -ორის კეთება არ მომიწევს

**Comment by davidgabrichidze** [comment]
Translation-ს თუ ვენდობით ხარისხში, მაშინ ოკეი. @Alexand227 ელზა თუ დათანხმდა კი ბატონო.

პირადად ჩემი პოზიციაა, რომ ორ ორი ველი იყოს

**Comment by Alexand227** [comment]
საკითხი გადაჭრილია, მრავალენოვანი ფუნქციის მხარდაჭერით.
