### ISSUE TITLE
ბმა ვორკნეტთან. როგორ?

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#16]

**Comment by davidgabrichidze** [comment]
აქ რა არის საჭირო? ლინკი ვორკნეტის გვერდებზე?

**Comment by Alexand227** [comment]
ზუსტად არ ვიცი ელზას რა და როგორ წარმოუდგენია. ჩემი მოსაზრებაა რომ იყოს ვორქნეტი. 
ამ კვირაში შევეხმიანები. მანამდე ნიკოს ცხრილებს შევქმნით სისტემაში და კიდევ თუ არის რამე მასალა დავდებთ.

**Comment by Alexand227** [comment]
გავაკეთეთ ლინკი ვორკნეტთან. ჯობ ფაინდერზე, როდესაც დადგება ადამიანი. თუ რამე სხვა ფუნქცია უნდა ელზას გვითხრას. სამშაბათის შეხვედრაზე დავსვავ აღნიშნულ საკითხს
