### ISSUE TITLE
იუზერ მენეჯმენტთან მიბდა და სისტემაში დალოგინება

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#17]

**Comment by Alexand227** [comment]
ვაჟიკ, 2 როლი შექმენი. ადმინისტრატორის, რომ მომხმარებლები გახსნას და მომხმარებლის, რომ ცხრილები შექმნას

**Comment by Zhestokus** [comment]
პრობლემა
ფორუმი ვერ მიბმევა ჩვენს UserManagements

**Comment by Zhestokus** [comment]
ხოლო პორტალი გაკეთებულია (უკვე არის UM-ზე მიბმული და ავტორიზაციის გარეშე ადმინს არ აჩვენებს)
