### ISSUE TITLE
Export-ის ღილაკი რეპორტებში

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#18]
იყოს ერთი ღილაკი (მაგალითად ისარი ქვემოთ დახრილი), რომლიდანაც მოხდება არჩევა, ექსელში გვინდა ჩამოტვირთვა, ჯპგ, ცსვ თუ კიდე რაში?

**Comment by Alexand227** [comment]
ანალოგიურად როგორც ჩართებზე.

**Comment by Zhestokus** [comment]
და რას ვქაჩავთ?
ცხრილის მონაცემებს თუ ჩარტს?

**Comment by Zhestokus** [comment]
გაკეთებულია

**Comment by Alexand227** [comment]
მარი, ღილაკი არის დასადები
