### ISSUE TITLE
დამჯგუფებელი ღილაკი

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#19]

**Comment by Zhestokus** [comment]
ვერ გავიგე

**Comment by davidgabrichidze** [comment]
მე მგონი ჩარტის ტიპებია. ასეა @Alexand227

**Comment by Alexand227** [comment]
იყოს ღილაკი (მაგალითად სვეტები), რომელიდანაც მოხდება არჩევა, თუ როგორი ტიპის ვიზუალში გვინდა ცხრილის გადაყვანა, თანაც თითოეულ ტიპზე იყოს ფორმა თ რას წარმოადგენს ეს ვიზუალური ეფექტი, წრეს, ხაზს თუ რას?

**Comment by Zhestokus** [comment]
გაკეთებულია
