### ISSUE TITLE
კომენტარის ველის 3 ნაწილად დაყოფა 

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#20]

**Comment by Alexand227** [comment]
კომენტარის ველი დაიყოს 3 ნაწილად; აღწერა, ინტერპრეტაცია და წყარო. შესაძლებელი იყოს კომენტარის ნაწილი იყოს თავში, ან იყოს ბოლოში

**Comment by Zhestokus** [comment]
gaketebulia
