### ISSUE TITLE
Popup-ის მხარდაჭერა ჩარტზე

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#22]
როდესაც ისარს მიიტან ჩარტთან კონკრეტულად სვეტთან ან ხაზთადნ პოპაპი ვარდებოდეს, სადაც დამატებით მნიშვნელობები გამოვა

**Comment by Alexand227** [comment]
@Zhestokus ალბათ გახსოვს პრეზენტაციიდან. 
იდეაში ეგ ფუნქციონალი თვითონ ექნება ჩარტებს

**Comment by Zhestokus** [comment]
გაკეთებულია
