### ISSUE TITLE
დევექსპრესის გრუპინგი ჩავრთოთ? 

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#23]

**Comment by davidgabrichidze** [comment]
@Alexand227 Pivot-ზე თუ ამბობ, ჩავრთოთ, რატომაც არა. გააჩნია რასთან არის კავშირში.

@Zhestokus  შენ ხედავ რაიმე პრობლემას?

**Comment by davidgabrichidze** [comment]
@Alexand227 ეს ინსტრუმენტი პირდაპირ არ არის მოთხვონილი ხომ? ესეც თუ კომფორტის საშუალებაა, ბოლოს მორჩენილი დროის შემთხვევაში ვაჩუქოთ.

**Comment by Alexand227** [comment]
ეს 2 წუთიანი საქმეა, უბრალოდ ამ ეტაპზე არ არის ბევრი მონაცემი, ეს ინსტრუმენტი კი ცოტა დიზაინს რევს და ამიტომ დავფიქრდი. თუმცა ფუნქციას უმატებს ცხრილებს

**Comment by Alexand227** [comment]
იდეაში პივოტია. უბრალოდ დიზაინს რევს

**Comment by Alexand227** [comment]
მოდი ჩავრთოთ, როცა ამის საჭიროება იქნება. ეხლა არ არის საჭირო და ტყუილად დიზაინს დაამძიმებს.
