### ISSUE TITLE
კლონ ფუქნცია

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#24]
კლონ ფუქნცია, რომლის დროსაც შესაძლებლობას გაძლევს ერთ გვერდზე 2 ჩართი გამოიტანო (ანუ აირჩიო რომელი ჩარტები გინდა შეადარო) თანაც იყოს ფუნქცია, რომ მიუთითო ჰორიზონტალურად გინდა, თუ ვერტიკალურად.

**Comment by davidgabrichidze** [comment]
@Alexand227 Issue-ს სათაური ჯობია იყოს მოკლე და დანარჩენი აღწერაში გაუშვა.

მაგალითად. 
სათაური: ჩარტების კლონის შესაძლებლობა
აღწერა:
ის რაც ახლა გიწერია სათაურში...

btw ეს კლონის ფუნქციაა თუ Dashboard-ის აწყობა?

**Comment by Alexand227** [comment]
ეს დაშბოარდის ნაწილია, თუმცა ნიკო პრეზენტაციაში იყნებდა ტერმინს კლონი და ზუსტად ვიცით რასაც გულისხმობდა. ამიტომაც გავუწერე, რომ ადვილი მისახვედრი ყოფილიყო ვაჟასთვის

**Comment by davidgabrichidze** [comment]
@Alexand227 ოკ, მაგრამ სათაური და აღწერა გადაანაწილე რა. პლიზ

**Comment by Zhestokus** [comment]
გაკეთებულია მაგრამ მუშაობს მხოლო კონფიგურაციაშია და საჭიროა Clone ღილაკის Icon
