### ISSUE TITLE
ჩარტის ლეგენტების განმარტებები

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#25]
ჩარტის ქვემოთ ეწეროს, თუ რას ნიშნავს X – Y , Z
დღეს როგორც გვაქვს, ისე არ უნდა დარჩეს

**Comment by Alexand227** [comment]
z ში ვგულიხმობ ლაინის მაგვარ მონაცემს. თუ იქნა მსგავსი რამ

**Comment by Zhestokus** [comment]
მემგონი უფრო სორი იქნება მაგას ჩარტის Description-ში თვითონ თუ მიაწერენ თორე მე იმაზე მეტის გამოტანა არ შემიძლია რაც ჩანს...
ჩემთვის არის X, Y, Z ველები რომლის სახელებიც ჩანს მაგრამ რას ნიშნავს ეს ველები მაგას პროგრამა როგორ გამოითანს?
ლოგიკას რო არ დავხატავ?!

**Comment by Zhestokus** [comment]
გაკეთებულია
