### ISSUE TITLE
საიტის ინგლისურად თარგმნა

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#27]
როგორც სტატიკური ნაწილების ასევე სხვადასხვა ტექსტების დამატებისას

**Comment by Zhestokus** [comment]
ოპტიმიზირებულია MultiLanguage-თვის
@Mari-a შენ იცი როგორც უნდა გადაითარგმნოს (URL-ში დაამატე პარამეტრი TranslationMode=1)
და თუ რომელიმე სიტყვა  თარგმნადი არ არის უბრალოდ
<ce:Label runat="server">/ce:Label
ტეგში ჩასვი
P.S ყურადღება მიაქციე ID-ებს
Label1, Label2, Label3 და ესეთი ID-ები არ ჩაგრჩეს  ID ვაბშე წაუშალე როგორც მაგალითში მიწერია
ასევე სათარგმნი გვერდი
http://localhost/Molhsa/Lmis/CITI.EVO.CommonData.Web/Pages/TranslationsList.aspx

**Comment by Mari-a** [comment]
დაწყებული მაქვს მუშაობა მოცემულ საკითხზე

**Comment by Alexand227** [comment]
იდეაში, საიტის ინგლისური ვერსია უკვე შექმნილია და სადაც ინქება თარგმანები დარჩენილი იმ ნაწილებს გავწერ
