### ISSUE TITLE
მონაცემი პირდაპირ არ წააშლევინოს, სანამ არ შეეკითხება სისტემა

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#30]

**Comment by davidgabrichidze** [comment]
@Alexand227 ეს ზოგადი ფუნქციაა, თუ კონკრეტულად სადმეა ხარვეზი?

**Comment by Alexand227** [comment]
ეს არის ზოგადი ფუნქცია. დიზაინის სწორების დროს, შემტხვევით “შემოგვეშალა” მონაცემი :) და მივხვდით, რომ არ იყო დამატებული ეს ფუნქცია

**Comment by Zhestokus** [comment]
gaketebulia

**Comment by Alexand227** [comment]
ვაჟიკ, გაშლევინებს პირდაპირ, როდესაც ადმინით შევდივარ. ასევე არ გეუნება, რომ დაემატა კატეგორია. უნდა იყოს შესაბამისი პოპაპი

**Comment by Zhestokus** [comment]
წაშლის თემა გავასწორე მაგრამ დამატებას რაც შეეხება ცხრილში ხო ჩანს რო დაემატა?
კიდევ რამე შეტყობინება გამოვიტანო რო წარმატებით დაემატა?
