### ISSUE TITLE
ნიკოს გამოგზავნილი ექსელის ცხრილის ატვირთვა სისტემაში

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#32]
@Zhestokus  ერთად შევყაროთ

**Comment by Zhestokus** [comment]
monacemebi shevyare, logikebi davamate magram chartebs ver vamateb dizainis gamo

@Mari-a 
![capture](https://cloud.githubusercontent.com/assets/10868142/19436234/fd1d00e8-947f-11e6-8974-c5ea0a497fa2.PNG)
popupze DropDown-ebis marjvniv aris damatebis gilaki romelic ar chans

**Comment by Mari-a** [comment]
დიზაინი გასწორებულია

**Comment by Zhestokus** [comment]
მონაცემებიც შეყრილია, ჩართებიც დმატებულია
