### ISSUE TITLE
მონაცემების გვერდზე ფილტრების აიქონების ცვლილება

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#40]
მარი,
მონაცემების გვერდზე, რომ გადადიხარ ეხლა არის 4 ფილტრი. მაქვს რამოდენიმე თხოვნა
1. ექსელის ნაცვლად იყოდ დაუნლოად ღილაკი
2. შემდეგ არის ორი ფილტრის აიქონი - მის ნაცვლად ერტი იყოს x და მეორე იყოს y აიქონი
3. ბოლო აიქონი, რომლითაც ვირჩევთ გრაფიკის ტიპს იყოს აიქონი ცოტა გაუგებია და გთხოვ, რომ სხვანაირი დასვა.
4. როდესაც გრაფიკებს ვირჩევთ და ამოდის პოპაპი, უნდა ეწეროს არა ფილტრი არამედ Charts Type

**Comment by Mari-a** [comment]
დამატებულია ღილაკები
1. როდესაც გრაფიკებს ვირჩევთ და ამოდის პოპაპი, უნდა ეწეროს არა ფილტრი არამედ Charts Type

ვაჟა ყველა პოპაპს აქვს ერთნაირი დასახელება და შესაცვლელია ღილაკის შესაბამისად
