### ISSUE TITLE
დოკუმენტების საიტზე წაკითხვა

### ISSUE THREAD

**Issue by Mari-a** [ugt-software/LMIS#41]
როდესაც ატვირთულ დოკუმენტებს ვაკლილკებთ სხვადასხვა კატეგორიაში, მაგ. კანონმდებლობაში, დოკუმენტი გაიხსნას ცალკე ფანჯარაში და არ ჩამოიტვირთოს ავტომატურად.

**Comment by Mari-a** [comment]
დოკუმენტები ატვირთულია pdf ფორმატში, ლინკზე დაჭერისას კონვერტირდება ashx ფორმატში, და გახსნისას გეკითხბა ფორმატის არჩევას, თუ შეიძლება რომ არ შეიცვალოს ატვირთული დოკუმენტის ფორმატი.

**Comment by Zhestokus** [comment]
გასწორებულია
