### ISSUE TITLE
Demo website

### ISSUE THREAD

**Issue by davidgabrichidze** [ugt-software/LMIS#48]
http://evolution.ge/Molhsa/Lmis/Lmis.Portal.Web ამ მისამართზე აღარ დევს დემო??

**Comment by Alexand227** [comment]
@davidgabrichidze კი დავით, ისევ ამ მისამართზ დევს. ეხლაც ვნახე

**Comment by davidgabrichidze** [comment]
კი, ახლა მუშაობს. იმ დღეს იყო გათიშული
