### ISSUE TITLE
ლოგოს ფონტის ცვლილება

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#49]
მარი, 
სამინისტრომ გვთხოვა 

გიგზავნი გუგლის ფონტს ლოგოსათვის, რომელიც მოცემულია ვებ-გვერდზე
https://fonts.google.com/?selection.family=Cutive+Mono|Inconsolata|Open+Sans|Roboto|Source+Sans+Pro
Source Sans Pro ან Inconsolata

ქართული ფონტებიდან
AKolkhetyN Italic
http://fonts.ge/en/font/690/AKolkhetyN-Italic
ან
ALK Sanet
http://fonts.ge/en/font/704/ALK-Sanet

ორივე შემთხვევაში უმჯობესია, რომ ფონტი იყოს დახრილი.
თანაც არ დაგავიწყდეს, რომ ლოგო თავშია გადმოსატანი. მე მგონი გაკეთებულიც გაქვს და დაქომითებული არ არის მე მგონი ხომ?

**Comment by Mari-a** [comment]
კი ალეკო, გაკეთებული გვაქვს, შევცვლი ფონტსაც და დავაქომითებ

**Comment by Mari-a** [comment]
დაქომითებულია
