### ISSUE TITLE
კალენდარი მთავარ გვერდზე

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#55]
გავაქროთ აგრეთვე ვაკანსიის ღილაკი და ვაკანსიის ღილაკის და საიტის შეფასების ღილაკის ადგილზე ჩავსვათ კალენდარი

**Comment by Zhestokus** [comment]
დამატებულია, სტილებია დასასმელი

**Comment by Mari-a** [comment]
Done
