### ISSUE TITLE
"კანონმდებლობა" ტაბის დაყოფა

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#58]
კანონმდებლობა კატეგორიაში გაჩნდეს 3 ქვეკატეგორია. კანონები, დადგენილებები, კონვენციები, რომლის ქვეშაც აიტვირთება შესაბამისი დოკუმენტაციები

**Comment by Mari-a** [comment]
ვაჟა, ადმინისტრირების მხარეს არის შესაბამისი ფუნქციონალი დასამატებელი

**Comment by Zhestokus** [comment]
გაკეთებულია
