### ISSUE TITLE
ლინკები სამთავრობო კატეგორიისათვის

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#59]
სამთავრობო ვებ-გვერდები
http://gov.ge
https://www.president.gov.ge/ge
http://www.parliament.ge/ge
http://www.moh.gov.ge
http://ssa.gov.ge
http://www.mes.gov.ge
http://www.economy.gov.ge
http://www.mof.ge
http://www.energy.gov.ge
http://www.justice.gov.ge
http://mfa.gov.ge
http://moa.gov.ge
http://www.eu-nato.gov.ge
http://www.mrdi.gov.ge/ge/main
http://www.mod.gov.ge

**Comment by Mari-a** [comment]
ატვირთულია
