### ISSUE TITLE
ნიუსი - ფაილია ასატვირთი

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#63]
მარი, კატეგორიაში  ჩვენს შესახებ ასატვირთია ფაილი "ნიუსი" რომელი კატეგორი "code" ში შეგიძლია ნახო

**Comment by Mari-a** [comment]
საჭიროა გაკეთდეს ადმინისტრატორის ნაწილი, 

გვერდი მოიცავს დასახელებას ტექსტს,

მარჯვენა მხარეს განთავსდება ნიუსების ჩამონათვალი რომელიც მოიცავს:

დასახელება, თარიღი, მოკლე აღწერა.
