### ISSUE TITLE
კატეგორია - საინფორმაციო ცენტრის ცვლილება

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#66]
კატეგორია „საინფორმაციო ცენტრი“ შეიცვალოს „აირჩიე შენი პროფესია“ და გადავიდეს პროფესიების ვიდეოების ბმულზე - http://myprofession.gov.ge/videos

**Comment by Mari-a** [comment]
ბანერი შევცვალე, გალინკვის ფუნქციონალს ვაჟა დაამატებს

**Comment by Zhestokus** [comment]
გაკეთებულია
