### ISSUE TITLE
მასალები - "საქართველო ციფრებში"

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#67]
კატეგორიაში - „საქართველო ციფრებში“ განთავსდეს
დასაქმებისა და უმუშევრობის ტენდენციები საქართველოში.

ვტვირთაფ ფაილს #

**Comment by Alexand227** [comment]
ვტვირთვ ფაილს "საქართველო ციფრებში"

**Comment by Mari-a** [comment]
ვაჟა საჭიროა ადმინისტრირებადი გახდეს ფაილის ატვირთვა შესაბამის ბანერზე
