### ISSUE TITLE
ჩარტებია შესაქმნელი და დოკუმენტი ასატვირთი

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#73]
ვაჟიკ, 
ჯითჰაბზე ფაილებსი ფოლდერში არის ექსელის ფაილი labour market survey - მაგ ფაილის მიხედვით უნდა ააგო რამოდენიმე ჩართი ხოლო, რომელსაც კომენტარში გაუწერ, რომ დამატებითი ინფომრაცია შესაძლოა მიიღონ დოკუმენტიდან და ლინკი. ხოლო რაც შეეხება თუ რომელ დოკუმენტზე ლინკი, ისიც ამავე ფოლდერში და ქვია 33 ანგარიში...

ვიცი, ეხლა, რომ შეკითხვები გექნება და ოფისში ყოფნის დროს გავიაროთ

ალეკო

**Comment by Zhestokus** [comment]
გაკეთებულია
