### ISSUE TITLE
შედარების ინტერფეისზე ცხრილის სიგანე

### ISSUE THREAD

**Issue by Mari-a** [ugt-software/LMIS#75]
შედარების ონტერფეისზე ცხრილის სიგანე მცირდება ავტომატურად იგივე % ით შემცირდეს ცხრილის სიგრძეც

**Comment by Zhestokus** [comment]
მარი მომწერე ზომები

**Comment by Mari-a** [comment]
width: 700px
height: 600px

**Comment by Zhestokus** [comment]
გაკეთებულია
