### ISSUE TITLE
რეპორტებს გადაერქვას სახელი და 2 დონე დაემატოს

### ISSUE THREAD

**Issue by Mari-a** [ugt-software/LMIS#80]
რეპორტებს გადაერქვას სახელი და დავარქვათ კვლევები 

ისეთივე სტრუქტურის უნდა იყოს როგორც კანონმდებლობა, დაემატოს კატეგორია და კატეგორიაში ბმულები

**Comment by Mari-a** [comment]
სახლი გადავარქვი.

ვაჟა ისეთივე სტრუქტურის უნდა იყოს როგორც კანონმდებლობა, დაემატოს კატეგორია და კატეგორიაში ბმულები

**Comment by Zhestokus** [comment]
გაკეთებულია
