### ISSUE TITLE
ადმინის მხარეს უკეთ ორგანიზება, მგალითად პოპულარული საიტების ნახვა

### ISSUE THREAD

**Issue by Alexand227** [ugt-software/LMIS#9]
მოსაფიქრებელია, გვინდა? ტექნიკურ დავალებაში არ წერია

**Comment by Alexand227** [comment]
კარგი ფუნქციაა, თუ ძნელი გასაკეთებელი არ არის. არ გვაქვს მსგავსი ტექნიკური მოთხოვნა. რას ფიქრობ @davidgabrichidze?

**Comment by davidgabrichidze** [comment]
@Alexand227 @Zhestokus რაც ტექნიკურ მოთხოვნაში არ არის - მისი გაკეთება, კანონმდებლობის მიხედვით არც შეიძლება, თუმცა თუ საკმარისი დრო დაგვრჩება ვაჩუქოთ. ჯერჯერობით მოთხოვნილ ფუნქციონალს ვაკეთებთ.

**Comment by Alexand227** [comment]
გასაგებია და მისაღებია
